# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cc's Blog
email: zchan0@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://minesecret.space/" # the base hostname & protocol for your site, e.g. http://example.com

# social accounts
twitter_username: zcchan0
github_username:  zchan0

# disqus
disqus:
    shortname: celiaz

# google
google_analytics: UA-110171624-1

# SEO
social:
  name: zchan0
  links:
    - https://twitter.com/zcchan0
    - https://www.douban.com/people/theyear/
    - https://instagram.com/zcccen/
    - https://github.com/zchan0

webmaster_verifications:
  google: Y-N00pF2QURAC9CB1siydx97irNc6FwVYMSx6lhrOSw

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-compose
  - jekyll-sitemap


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
